### PR TITLE
Please Help me on this

### PR DESCRIPTION
**Pull request by ranjitkumar518**
Sorry to create file like this. This is blocking me. Please help me on this issue.

### CODE REVIEW

**Comment by openstack-gerrit** [comment]
Thank you for contributing to openstack-infra/jenkins-job-builder!

openstack-infra/jenkins-job-builder uses Gerrit for code review.

If you have never contributed to OpenStack before make sure you have read the
getting started documentation:
http://docs.openstack.org/infra/manual/developers.html#getting-started

Otherwise please visit
http://docs.openstack.org/infra/manual/developers.html#development-workflow
and follow the instructions there to upload your change to Gerrit.

**Comment by hayderimran7** [comment]
@ranjitkumar518 the error `File "/usr/local/lib/python2.7/site-packages/jenkins_jobs/modules/builders.py", line 2019, in gen_xml
 +    for builder in data[alias]:` suggests its coming from your `builder:` script, not this publisher. i tested this publisher and it threw a different error for me 
```
    kind = cdata['condition-kind']
TypeError: string indices must be integers, not str
```

**Comment by ranjitkumar518** [comment]
Hi @hayderimran7 ,
I am sorry. I am also getting the same error(mistakenly posted wrong error). my intention is to create  a maven job with a post build step(not post build action) to trigger a job after maven build with conditional step. Here is my updated code. It is working fine but it is triggering a job in post build action(difference is block down stream option is not available in post build action). can you review my code and suggest some changes or example to trigger a job in post build step with conditional step as always success and block the triggered job. I also tried below commented code. Please give inputs to trigger a job in post-build-step.

- job:
    name: 'maven_job'
    project-type: maven
    description: "Modified job"
    parameters:
      - string:
         name: branch
         default: master
         description: "Branch Selector"
    scm:
      - git:
          url: https://github.com/ranjitkumar518/myfirstrepo.git
          branches:
            - '${branch}'
    maven:
        maven-name: maven-3.2.1
        root-pom: pom.xml
        goals: clean package
    publishers:
       - conditional-publisher:
           - condition-kind: current-status
             condition-worst: SUCCESS
             condition-best: SUCCESS
             on-evaluation-failure: fail
             action:
               - trigger-parameterized-builds:
                   - project: test_job
                      current-parameters: true
                      trigger-with-no-params: false
    # builders:
    # - conditional-step:
     #     condition-kind: current-status
      #    condition-worst: SUCCESS
       #   condition-best: SUCCESS
        #  steps:
         #     - shell: "whoami"

**Comment by hayderimran7** [comment]
@ranjitkumar518  ah i found the issue - you were missing a `-` before the `condition-kind` and also your alignment is messed up. the following worked me 👍 
```
- publisher:
    name: test
    publishers:
      - conditional-publisher:
          - condition-kind: current-status
            condition-worst: FAILURE
            condition-best: SUCCESS
            action:
               - trigger-parameterized-builds:
                   - project: default_job
                     current-parameters: true
                     trigger-with-no-params: false
```
again please be very mindful of yaml alignment , hope it works !

**Comment by hayderimran7** [comment]
use the above as a publisher in your job configuration as : 
```
- job:
     name: 'maven_job'
     project-type: maven 
     description: "Modified job"
    ....
.....
....
     publishers:
        - test 
```

**Comment by ranjitkumar518** [comment]
Hi @hayderimran7,

Thanks for looking in my issue. 
This code is triggering a job in post-build action. I want to trigger job in post-build step after maven build. The difference between post-build action and post-build step is we cant block the down-stream job. please find the attached screenshot for your reference.

present-output
required-output

**Comment by hayderimran7** [comment]
do you wana use parameterized trigger or not? in the original posted, you have `trigger-parameterized` and thats the same i provided you.  and now you say you wana use `build other projects` - two different things. which one you want? im confused -

**Comment by ranjitkumar518** [comment]
I want to trigger a build with parameters. I tried trigger-builds option(where we can pass predefined-parameters) option also. But internal to the publisher it is not allowing me only this trigger-parameterized-build option.

**Pull request closed without merging**
